package Forms;


import Utilities.SQLiteDbManager;
import Utilities.Constants;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ALI
 */
public class NewAP extends javax.swing.JDialog {
    
    private boolean changes = false;
    
    /**
     * Creates new form NewAP
     */
    public NewAP(JFrame parent) {
        super(parent);
        initComponents();
    }
    
    public boolean showDialog() {
        setVisible(true);
        return changes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfModel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfBrand = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfRefPow = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfRefDist = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btCancel = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(350, 240));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel1.setText("Model:");

        tfModel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel2.setText("Brand:");

        tfBrand.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel3.setText("Emission Power:");

        tfRefPow.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        tfRefPow.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfRefPowKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel4.setText("dBm");

        tfRefDist.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        tfRefDist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfRefDistKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel5.setText("Path loss at 1m:");

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel6.setText("dBm");

        btCancel.setText("Close");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        btAdd.setText("Add");
        btAdd.setMaximumSize(new java.awt.Dimension(69, 32));
        btAdd.setMinimumSize(new java.awt.Dimension(69, 32));
        btAdd.setPreferredSize(new java.awt.Dimension(69, 32));
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfModel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRefDist))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRefPow)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRefPow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRefDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancel))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        if(tfModel.getText().equals("") || tfBrand.getText().equals("") || tfRefPow.getText().equals("") || tfRefDist.getText().equals(""))
        JOptionPane.showMessageDialog(this, Constants.MISSING_FEILDS_MSG, Constants.MISSING_FEILDS_TITLE, JOptionPane.ERROR_MESSAGE);
        else{
            try{
                int i = SQLiteDbManager.ExecuteNonQuery(SQLiteDbManager.connect(),
                    "INSERT INTO Access_Point (Brand, Model, Emission_Power, Path_Loss_1M) VALUES ('" + tfBrand.getText() + "', '" + 
                            tfModel.getText() + "', " + tfRefPow.getText() + ", " + tfRefDist.getText() + ")");
                if (i == 0)
                JOptionPane.showMessageDialog(this, Constants.NEWAP_ERROR_MSG, Constants.NEWAP_ERROR_TITLE, JOptionPane.WARNING_MESSAGE);
                else{
                    JOptionPane.showMessageDialog(this, Constants.NEWAP_SUCCESS_MSG, Constants.NEWAP_SUCCESS_TITLE, JOptionPane.INFORMATION_MESSAGE);
                    tfRefDist.setText("");
                    tfRefPow.setText("");
                    tfBrand.setText("");
                    tfModel.setText("");
                    changes = true;
                    //this.DialogResult = DialogResult.OK;
                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, Constants.NEWAP_ERROR_MSG, Constants.ERROR, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void tfRefDistKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRefDistKeyTyped
        if (!evt.isControlDown() && !Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.' && evt.getKeyChar() != '-') {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }// only allow one decimal point
        else if (evt.getKeyChar() == '.' && tfRefDist.getText().indexOf('.') > -1) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_tfRefDistKeyTyped

    private void tfRefPowKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRefPowKeyTyped
        if (!evt.isControlDown() && !Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.' && evt.getKeyChar() != '-') {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }// only allow one decimal point
        else if (evt.getKeyChar() == '.' && tfRefPow.getText().indexOf('.') > -1) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_tfRefPowKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfBrand;
    private javax.swing.JTextField tfModel;
    private javax.swing.JTextField tfRefDist;
    private javax.swing.JTextField tfRefPow;
    // End of variables declaration//GEN-END:variables
}
