/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author ALI
 */
public class PanelHeatMap extends javax.swing.JPanel {

    /**
     * Creates new form PanelHeatMap
     */
    public PanelHeatMap() {
        initComponents();
    }
    
    @Override
    public void paint(Graphics grphcs) {
        super.paint(grphcs); //To change body of generated methods, choose Tools | Templates.
        
        double value = 1, step = 3 / (double)(getWidth() - 20);
        
        for(int i = 10; i < getWidth() - 10; i+=3){
            
            grphcs.setColor(new Color((float)(value), (float)((4 * value * (1 - value))), (float) ((1 - value))));
            grphcs.fillRect(i, getHeight()/2, 3, getHeight()/2);
            value -= step;
        }
        
        grphcs.setColor(Color.BLACK);
        grphcs.fillRect(10, getHeight() / 2, 1, 16);
        grphcs.fillRect(getWidth() / 4 + 5, getHeight() / 2, 1, 8);
        grphcs.fillRect(getWidth() / 2, getHeight() / 2, 1, 16);
        grphcs.fillRect(3 * getWidth() / 4 - 5, getHeight() / 2, 1, 8);
        grphcs.fillRect(getWidth() - 10, getHeight() / 2, 1, 16);
    }
    
    public void setMinThreshold(double minThreshold){
        lMax.setText("-30dBm");
        lHalf.setText((-30 + minThreshold) / 2 + "dBm");
        lQuart.setText(5 * (-30 + minThreshold) / 8 + "dBm");
        l3Quart.setText(3 * (-30 + minThreshold) / 8 + "dBm");
        lMin.setText(minThreshold + "dBm");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lMax = new javax.swing.JLabel();
        lMin = new javax.swing.JLabel();
        lHalf = new javax.swing.JLabel();
        lQuart = new javax.swing.JLabel();
        l3Quart = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 55));
        setPreferredSize(new java.awt.Dimension(600, 55));

        lMax.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        lMax.setText("Max");

        lMin.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        lMin.setText("Min");

        lHalf.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        lHalf.setText("Md");

        lQuart.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        lQuart.setText("Md");

        l3Quart.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        l3Quart.setText("Md");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lMax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(l3Quart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(lHalf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(lQuart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(lMin)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMax)
                    .addComponent(lMin)
                    .addComponent(lHalf)
                    .addComponent(lQuart)
                    .addComponent(l3Quart))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel l3Quart;
    private javax.swing.JLabel lHalf;
    private javax.swing.JLabel lMax;
    private javax.swing.JLabel lMin;
    private javax.swing.JLabel lQuart;
    // End of variables declaration//GEN-END:variables
}
